from alembic import op
import sqlalchemy as sa

def createDB():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csvjoinmap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_name', sa.String(), nullable=True),
    sa.Column('dlvrloadgndvsense0', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end csvjoinmap commands ###

    op.create_table('par_exe_csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_name', sa.String(), nullable=True),
    sa.Column('test', sa.String(), nullable=True),
    sa.Column('flopcnt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end par_exe_csv commands ###

    op.create_table('par_exe_mapfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dlvrloadgndvsense0', sa.String(), nullable=True),
    sa.Column('dlvrloadgndvsense02', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end par_exe_mapfile commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('csvjoinmap')
    # ### end Alembic commands ###
    op.drop_table('par_exe_csv')
    op.drop_table('par_exe_mapfile')